import { Inter } from "next/font/google";
import "rsuite/dist/rsuite-no-reset.min.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { CustomProvider } from "rsuite";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { NextUIProvider } from "@nextui-org/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextUIProvider>
        <body className={inter.className}>
          <Header />
          <CustomProvider>{children}</CustomProvider>
          <Footer />
        </body>
      </NextUIProvider>
    </html>
  );
}
