import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { LanguageProvider } from "../context/LanguageContext";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { NextUIProvider } from "@nextui-org/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextUIProvider>
        <LanguageProvider>
          <body className={inter.className}>
            <Header />
            <main>{children}</main>
            <Footer />
          </body>
        </LanguageProvider>
      </NextUIProvider>
    </html>
  );
}
